name: Build and execute Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Execute unit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo 'simstera'

  execute-ui-test:
    needs: build
    runs-on: ubuntu-latest
            
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Start the application
      run: npm run start &
    - name: Execute the ui tests
      run: npm run test:ui

  deployment-to-render:
    needs: execute-ui-test
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
    - uses: actions/checkout@v3
    - uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        wait_deploy: true